// ── CONFIG & DIFFICULTY ─────────────────────────────
        var CFG = { musicOn: true, sfxOn: true, musicVol: .5, sfxVol: .8, diff: 'normal', lang: 'vi' };
        var DIFF_MAP = {
            easy: { gm: .65, dm: 1.4, em: 1.5, fm: .65, labelVi: 'DỄ', labelEn: 'EASY', descVi: 'Mục tiêu giảm 35% · Thu nhập +50% · Ít mệt hơn', descEn: 'Goal -35% · Income +50% · Less fatigue' },
            normal: { gm: 1, dm: 1, em: 1, fm: 1, labelVi: 'BÌNH THƯỜNG', labelEn: 'NORMAL', descVi: 'Mục tiêu chuẩn · Thu nhập chuẩn · Mệt mỏi chuẩn', descEn: 'Standard goal · Standard income · Standard fatigue' },
            hard: { gm: 1.5, dm: .82, em: .85, fm: 1.3, labelVi: 'KHÓ', labelEn: 'HARD', descVi: 'Mục tiêu +50% · Thu nhập giảm · Mệt mỏi nhanh hơn', descEn: 'Goal +50% · Less income · Faster fatigue' }
        };
        function getDiffLabel() { return DIFF_MAP[CFG.diff][CFG.lang === 'en' ? 'labelEn' : 'labelVi']; }
        function getDiffDesc() { return DIFF_MAP[CFG.diff][CFG.lang === 'en' ? 'descEn' : 'descVi']; }
        var BASE_LVS = {
            minh: [
                { goal: 50000000, days: 30, story: 'daughter', label: 'Chương 1' },
                { goal: 150000000, days: 35, story: 'debt', label: 'Chương 2' },
                { goal: 300000000, days: 40, story: 'hospital', label: 'Chương 3' },
                { goal: 600000000, days: 45, story: 'shipper', label: 'Chương 4' }
            ],
            lan: [
                { goal: 30000000, days: 30, story: 'daughter', label: 'Chương 1' },
                { goal: 80000000, days: 35, story: 'debt', label: 'Chương 2' },
                { goal: 150000000, days: 40, story: 'hospital', label: 'Chương 3' },
                { goal: 300000000, days: 45, story: 'shipper', label: 'Chương 4' }
            ],
            hung: [
                { goal: 15000000, days: 30, story: 'daughter', label: 'Chương 1' },
                { goal: 50000000, days: 35, story: 'debt', label: 'Chương 2' },
                { goal: 100000000, days: 40, story: 'hospital', label: 'Chương 3' },
                { goal: 200000000, days: 45, story: 'shipper', label: 'Chương 4' }
            ],
            khanh: [
                { goal: 20000000, days: 30, story: 'daughter', label: 'Chương 1' },
                { goal: 60000000, days: 35, story: 'debt', label: 'Chương 2' },
                { goal: 120000000, days: 40, story: 'hospital', label: 'Chương 3' },
                { goal: 300000000, days: 45, story: 'shipper', label: 'Chương 4' }
            ]
        };
        function getLvs() {
            var d = DIFF_MAP[CFG.diff];
            var charKey = (typeof G !== 'undefined' && G.character) ? G.character : 'minh';
            var lvs = BASE_LVS[charKey] || BASE_LVS.minh;
            return lvs.map(function (l) {
                return { goal: Math.round(l.goal * d.gm / 1000000) * 1000000, days: Math.round(l.days * d.dm), story: l.story, label: l.label };
            });
        }
        function getDiff() { return DIFF_MAP[CFG.diff]; }

        // ── i18n LANGUAGE SYSTEM ─────────────────────────────
        var I18N = {
            vi: {
                // Menu
                newGame: 'NEW GAME', continueGame: 'CONTINUE', aiHealth: 'AI Dự Đoán Sức Khỏe',
                settings: 'CÀI ĐẶT', news: 'TIN TỨC', intro: 'GIỚI THIỆU', bestRuns: 'KỶ LỤC', subtitle: 'a story about the price of ambition',
                // Settings
                settTitle: '⚙ CÀI ĐẶT', settSub: 'GAME SETTINGS · v7.0',
                settSound: '🔊 ÂM THANH', settDiff: '⚔ ĐỘ KHÓ', settLang: '🌐 NGÔN NGỮ',
                settControls: '🎮 ĐIỀU KHIỂN', settSave: '💾 LƯU CÀI ĐẶT', settBack: '← QUAY LẠI',
                bgm: 'Nhạc nền', sfx: 'Hiệu ứng âm thanh',
                easy: 'DỄ', normal: 'BÌNH THƯỜNG', hard: 'KHÓ',
                move: 'Di chuyển', interact: 'Tương tác', menuClose: 'Menu / Đóng', moveAlt: 'Di chuyển (alt)',
                // HUD
                moneyLabel: '💰 TIỀN TÍCH LŨY', goalPrefix: 'Mục tiêu: ', daysLeft: ' ngày)',
                statusNormal: 'BÌNH THƯỜNG', statusTired: 'MỆT', statusWarning: 'CẦN CẨN THẬN', statusDanger: 'NGUY HIỂM',
                sleptYes: 'Đủ giấc', sleptNo: 'Chưa ngủ', cups: ' ly',
                talkTo: '[ E ] Nói chuyện với ', interactWith: '[ E ] ',
                // Game objects
                overtime: 'Tăng ca', project: 'Dự án', overnight: 'Cày đêm', freelance: 'Freelance',
                sleep: 'Ngủ', rest: 'Nghỉ ngơi', exercise: 'Thể dục', coffee: 'Quán Ăn', gaming: 'Chơi game', social: 'Mạng xã hội', doctor: 'Khám bệnh',
                descOT: '+$$ Tiền OT', descProject: '+$$$ Dự án', descOvernight: '+$$$$ Thức trắng', descFreelance: '+$$$ Freelance',
                descSleep: 'Hồi phục HP+Mệt', descRest: '-25% mệt + 5HP', descExercise: '+HP -Stress', descCoffee: 'Giảm mệt, tăng HP', descGaming: '-Stress +Vui', descSocial: '-Phí +Vui', descDoctor: '+30HP, -20% mệt',
                // Rooms
                roomOffice: '📋 VĂN PHÒNG', roomNight: '🌙 KHU LÀM ĐÊM',
                roomRest: '🛏 KHU NGHỈ NGƠI', roomCafe: '☕ CAFÉ & Y TẾ',
                // Difficulty desc
                easyDesc: 'Mục tiêu giảm 35% · Thu nhập +50% · Ít mệt hơn',
                normalDesc: 'Mục tiêu chuẩn · Mệt mỏi chuẩn · Thu nhập chuẩn',
                hardDesc: 'Mục tiêu +50% · Thu nhập giảm · Mệt mỏi nhanh hơn',
                // NPC advice
                npc1: ['Anh ơi coi chừng sức khỏe!', 'Mệt quá thì nghỉ đi, đừng cố!', 'Nhớ ngủ đủ giấc nhé.', 'Uống cà phê vừa thôi!'],
                npc2: ['Cẩn thận kiệt sức nhé anh!', 'Nên nghỉ ngơi một chút.', 'Sức khỏe quan trọng hơn tiền.', 'Chăm sóc bản thân đi anh.'],
                npc3: ['Đêm khuya rồi, về ngủ đi!', 'Đừng làm nhiều quá sập đó.', 'Kinh nghiệm cho thấy: ngủ đủ giúp làm việc hiệu quả hơn.', 'Cà phê nhiều quá hại tim lắm!'],
                npcChild: ['Ba ơi ba đừng làm việc quá sức nha!', 'Con muốn thấy ba cười, chứ không phải thấy ba mệt mỏi.', 'Ba nghỉ tay ôm con một xíu đi!', 'Ba ơi sức khỏe quan trọng nhất!'],
                npcMom: ['Mình nghỉ ngơi một chút đi anh.', 'Tiền bạc khó khăn nhưng anh đừng cố sức quá, em lo lắm.', 'Sức khỏe của anh là chỗ dựa cho mẹ con em.', 'Đừng ép cơ thể quá mức, hãy ngủ thêm một chút.'],
                backMenu: '← MENU', goalWord: 'còn ',
                // HUD labels
                hudEn: '⚡ NĂNG LƯỢNG', hudHp: '❤️ SỨC KHỎE', hudFat: '😴 MỆT MỎI',
                hudTi: '🕒 THỜI GIAN', hudHu: '🍚 ĐỘ NO', hudKn: '📚 TRI THỨC',
                hudDay: 'NGÀY', hudLv: 'LV',
                hudSleep: 'Ngủ hôm qua:', hudCoffee: 'Cà phê hôm nay:', hudStatus: 'Trạng thái:',
                hudWife: 'T/C Vợ:', hudDaug: 'T/C Con:',
                hwarn: '⚠ NGUY HIỂM — QUÁ MỆT MỎI!',
                chint: 'WASD: Di chuyển · E: Tương tác · F: Mở tủ đồ · ESC: Menu · ⏳ Thời gian theo giờ',
                wardrobe: 'Tủ đồ',
                // Mall items
                mall_jacket: 'Áo Khoác Da', mall_shoes: 'Giày Thể Thao', mall_teddy: 'Gấu Bông Lớn',
                mall_doll: 'Búp Bê Nhỏ', mall_lego: 'Bộ Lego Lớn', mall_flowers: 'Bó Hoa Tươi',
                mall_necklace: 'Dây Chuyền', mall_perfume: 'Nước Hoa Pháp', mall_ring: 'Nhẫn Kim Cương',
                mall_watch: 'Đồng Hồ Hiệu',
                evImpactLbl: 'PHÁT SINH CHI PHÍ', evConfirm: 'TÔI HIỂU — TIẾP TỤC →',
                evNewGoal: 'Mục tiêu mới: ', evDaysLeft: ' ngày)',
                // News labels
                newsHeader: 'TIN TỨC & <span>Y HỌC</span>',
                newsSubtitle: 'Cập nhật những thông tin y tế và sức khỏe mới nhất',
                newsMore: 'XEM THÊM',
                newsBack: 'QUAY LẠI MENU',
                // News Articles
                articles: [
                    { date: '27/12/2024', title: 'Bệnh tim mạch đang ngày càng trẻ hóa', desc: 'Mỗi năm có 200,000 người Việt tử vong vì bệnh này. Chuyên gia cảnh báo về lối sống hiện đại.', url: 'https://suckhoedoisong.vn/benh-tim-mach-dang-ngay-cang-tre-hoa-moi-nam-200000-nguoi-viet-tu-vong-vi-benh-nay-169241227211028683.htm', img: 'https://loremflickr.com/400/200/heart,disease/all?lock=1' },
                    { date: '15/01/2025', title: '7 tiến bộ lớn trong nghiên cứu tim mạch 2024', desc: 'Khám phá những công nghệ và phương pháp điều trị mới nhất trong năm qua.', url: 'https://thuocsuckhoe.vn/7-tien-bo-lon-trong-nghien-cuu-benh-tim-mach-nam-2024-546', img: 'https://loremflickr.com/400/200/research,medical/all?lock=2' },
                    { date: '01/02/2025', title: 'Thống kê Đột quỵ & Tim mạch 2025', desc: 'Bản cập nhật thống kê mới nhất từ Professional Heart về tình trạng đột quỵ toàn cầu.', url: 'https://professional.heart.org/-/media/phd-files-2/science-news/2/2025-heart-and-stroke-stat-update/stat-update-whats-new/2025-stats-update-whats-new-vietnamese.pdf', img: 'https://loremflickr.com/400/200/brain,stroke/all?lock=3' },
                    { date: '10/02/2025', title: 'Cơ chế gây bệnh tim mạch từ lối sống', desc: 'Nghiên cứu khoa học phân tích sâu về tác động của stress và thức khuya đến tế bào tim.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11786524/', img: 'https://loremflickr.com/400/200/lifestyle,health/all?lock=4' },
                    { date: '18/02/2025', title: 'Lancet: Gánh nặng đột quỵ toàn cầu', desc: 'Review chuyên sâu từ The Lancet về xu hướng và rủi ro thần kinh liên quan.', url: 'https://www.thelancet.com/journals/laneur/article/PIIS1474-4422(24)00363-6/abstract', img: 'https://loremflickr.com/400/200/hospital,neurology/all?lock=5' },
                    { date: '21/02/2025', title: 'AHA: Tác động của dinh dưỡng và vận động', desc: 'Bài báo từ Hiệp hội Tim mạch Hoa Kỳ về các yếu tố nguy cơ có thể thay đổi.', url: 'https://www.ahajournals.org/doi/10.1161/JAHA.124.039387', img: 'https://loremflickr.com/400/200/nutrition,running/all?lock=6' },
                    { date: '01/03/2025', title: 'Mối liên hệ giữa căng thẳng và nhồi máu cơ tim', desc: 'Liên tục làm việc dưới áp lực cao làm tăng 40% nguy cơ suy tim ở tuổi 30.', url: '#', img: 'https://loremflickr.com/400/200/stress,work/all?lock=7' },
                    { date: '05/03/2025', title: 'Chế độ ăn giảm 30% nguy cơ đột quỵ', desc: 'Nghiên cứu mới khẳng định việc ăn nhiều rau củ cứu sống hàng triệu người.', url: '#', img: 'https://loremflickr.com/400/200/vegetables,salad/all?lock=8' },
                    { date: '10/03/2025', title: '30 phút nỗ lực: Chìa khóa cho hệ tuần hoàn', desc: 'Không cần tập gym cường độ cao, chỉ cần đi bộ nhanh cũng đủ bảo vệ tim mạch.', url: '#', img: 'https://loremflickr.com/400/200/exercise,walking/all?lock=9' },
                    { date: '18/03/2025', title: 'Thiếu ngủ và sự hủy hoại các nơ-ron', desc: 'Ngủ ít hơn 5 tiếng mỗi đêm đẩy nhanh quá trình sa sút trí tuệ và lão hóa não bộ.', url: '#', img: 'https://loremflickr.com/400/200/sleep,bed/all?lock=10' },
                    { date: '22/03/2025', title: 'AI trong chẩn đoán sớm hình ảnh đột quỵ', desc: 'Công nghệ AI phát hiện các cục máu đông với độ chính xác lên tới 98%.', url: '#', img: 'https://loremflickr.com/400/200/technology,AI/all?lock=11' },
                    { date: '25/03/2025', title: 'Nước tăng lực và nhịp tim rối loạn', desc: 'Lạm dụng đồ uống có caffeine làm tăng nguy cơ rối loạn nhịp tim đột ngột.', url: '#', img: 'https://loremflickr.com/400/200/energydrink,heart/all?lock=12' },
                    { date: '28/03/2025', title: 'Tác hại của việc ngồi liên tục 8 tiếng', desc: 'Ngồi lỳ một chỗ được ví như hút thuốc kiểu mới, tăng rủi ro thuyên tắc mạch.', url: '#', img: 'https://loremflickr.com/400/200/sitting,office/all?lock=13' }
                ],
                // App content section
                acHeader: 'GIỚI THIỆU <span>CÔNG NGHỆ AI</span>',
                acSub: 'Khám phá sức mạnh của trí tuệ nhân tạo trong việc bảo vệ sức khỏe và kéo dài tuổi thọ.',
                acC1T: 'Tầm Soát Rủi Ro & Đột Quỵ',
                acC1D: 'Sử dụng các mô hình học máy để phân tích triệu chứng và phát hiện sớm các dấu hiệu nguy cơ về tim mạch và thần kinh.',
                acC2T: 'Phân Tích Lối Sống Thông Minh',
                acC2D: 'Đánh giá tác động của thói quen ngủ, cường độ làm việc và dinh dưỡng đến sức khỏe nền tảng của bạn.',
                acC3T: 'Dự Đoán Sức Khỏe Toàn Diện',
                acC3D: 'Học máy đánh giá nguy cơ đột quỵ và dự đoán sức khỏe tổng quát dựa trên bộ tiêu chuẩn WHO/AHA và các chỉ số cơ thể thực tế.',
                acC4T: 'Bác Sĩ Trình Lang AI 24/7',
                acC4D: 'Hỗ trợ giải đáp triệu chứng lâm sàng, cung cấp kiến thức sơ cứu và hướng dẫn phòng ngừa các biến cố sức khỏe ngay tức thì.',
                // AI screen
                aiTag: 'HEALTH MONITOR AI · v2.4', aiTitle: 'AI DỰ ĐOÁN SỨC KHỎE',
                aiDesc: 'Nhập thông tin lối sống để AI phân tích sức khỏe và đưa ra cảnh báo rủi ro.',
                aiSectionBasic: 'THÔNG TIN CƠ BẢN', aiSectionSleep: 'THÓI QUEN NGỦ',
                aiSectionDiet: 'ĂN UỐNG & VẬN ĐỘNG', aiSectionRisk: 'HÀNH VI RỦI RO',
                aiSectionExtra: 'MÔ TẢ THÊM (tùy chọn)',
                aiSubmit: '🧬 PHÂN TÍCH NGAY', aiDisclaimer: '⚠ Mô phỏng AI — Không phải chẩn đoán y khoa',
                aiAnalysisHeader: 'HEALTH ANALYSIS SYSTEM',
                aiAgeLbl: 'TUỔI HIỆN TẠI', aiJobLbl: 'NGHỀ NGHIỆP', aiHeightLbl: 'CHIỀU CAO (cm)', aiWeightLbl: 'CÂN NẶNG (kg)',
                aiCamVerify: '📸 XÁC MINH BẰNG KHUÔN MẶT', aiCamStart: '📷 Mở Camera', aiCamCapture: '📸 CHỤP', aiCamClose: '✕ Đóng', aiCamDone: '✅ Đã chụp — AI sẽ ước lượng tuổi', aiCamRetry: '🔄 Chụp lại',
                aiGenderLbl: 'GIỚI TÍNH', aiMale: 'Nam', aiFemale: 'Nữ', aiBmiLbl: 'BMI (kg/m²)', aiSleepLbl: 'GIỜ NGỦ MỖI ĐÊM', aiBedtimeLbl: 'THƯỜNG THỨC ĐẾN MẤY GIỜ?',
                aiBed: ['Trước 10h tối', '11h tối', 'Nửa đêm', '1h sáng', '2-3h sáng', 'Sau 4h sáng'],
                aiSleepBadLbl: 'NGÀY THIẾU NGỦ / TUẦN', aiDietLbl: 'CHẾ ĐỘ ĂN UỐNG',
                aiDiet: ['Rất lành mạnh', 'Tương đối lành mạnh', 'Trung bình', 'Nhiều đồ chiên, fast food', 'Rất tệ'],
                aiExeLbl: 'TẬP THỂ DỤC / TUẦN', aiExe: ['5+ ngày/tuần', '3-4 ngày/tuần', '1-2 ngày/tuần', 'Không bao giờ'],
                rcSmoking: '🚬 Hút thuốc', rcAlcohol: '🍺 Rượu nhiều', rcStress: '😰 Stress mãn tính', rcOverwork: '💼 Làm >12h/ngày', rcNoSocial: '🚫 Cô lập xã hội',
                rcCaffeine: '☕ >4 ly cà phê/ngày', rcInsomnia: '🌙 Thức trắng 2 ngày', rcSkipMeal: '🍽 Bỏ ăn thường xuyên', rcGameAbuse: '🎮 Lạm dụng game >6h/ngày',
                rcNoBreak: '⚠ Làm liên tục không nghỉ', rcSleep3h: '😴 Ngủ dưới 3 tiếng', rcLongStress: '🧠 Stress kéo dài >3 tháng', rcSedentary: '🪑 Không vận động cả ngày', rcEnergy: '⚡ Lạm dụng nước tăng lực',
                aiExtraLbl: 'MÔ TẢ THÊM (tùy chọn)', aiExtraPlc: 'VD: Thường ngủ muộn, ít vận động...', aiIdleTxt: 'Điền thông tin và nhấn<br>PHÂN TÍCH NGAY',
                aiAnalyzing: '⏳ ĐANG PHÂN TÍCH...', aiAnalyzingData: 'ĐANG PHÂN TÍCH DỮ LIỆU...', aiScanning: 'ĐANG QUÉT...',
                aiEstLife: 'TUỔI THỌ ƯỚC TÍNH', aiYearsOld: 'tuổi', aiRiskLevel: 'MỨC ĐỘ RỦI RO', aiImprove: '↑ CẢI THIỆN', aiDecline: '↓ SUY GIẢM',
                aiRiskHealth: 'RỦI RO SỨC KHỎE', aiWarnDanger: '⚠ CẢNH BÁO', aiWarnGood: '✅ TÍCH CỰC', aiDetailAI: 'PHÂN TÍCH CHI TIẾT · AI',
                warnSmoking: 'Hút thuốc lá giảm 8-10 năm tuổi thọ.', warnInsomnia: 'Thức trắng 2 ngày tăng nguy cơ đột quỵ 300%.', warnSleep3h: 'Ngủ dưới 3h phá hủy hệ miễn dịch.',
                warnNoBreak: 'Làm liên tục không nghỉ gây kiệt sức mãn tính.', warnLongStress: 'Stress kéo dài gây tổn thương tim mạch.', warnSkipMeal: 'Bỏ ăn thường xuyên gây suy dinh dưỡng.',
                warnSleepLess6: 'Ngủ ít hơn 6h gây tổn hại nghiêm trọng.', warnOverwork: 'Làm việc quá 12h/ngày tăng nguy cơ đột quỵ.', warnBmiHigh: 'BMI cao tăng rủi ro tim mạch.',
                warnManyRisks: '⚠ QUÁ NHIỀU YẾU TỐ RỦI RO — nguy cơ tích lũy rất cao!', warnGoodHabit: 'Lối sống hiện tại khá tốt, tiếp tục duy trì!',
                warnDefaultGood: 'Sức khỏe đang trong tình trạng tốt.', warnDefaultBad: 'Cần cải thiện lối sống ngay.',
                aiExplain1: 'Phân tích ', aiExplain2: ' yếu tố rủi ro, BMI ', aiExplain3: ', ngủ ', aiExplain4: 'h/đêm.', aiExplain5: 'Hãy duy trì thói quen tốt và tránh các yếu tố có hại.',
                // Story
                storyDaughter: { chapter: 'Chương 1 · Người Cha', title: 'Vì <span style="color:#ffd700">Con Gái</span> Nhỏ', text: 'Minh, 38 tuổi, nhân viên văn phòng bình thường.\n\nCon gái anh — bé Linh, 7 tuổi — vừa bị tai nạn gãy chân, cần phẫu thuật chấn thương chỉnh hình gấp.\n\nChi phí ban đầu: <b style="color:#ffd700">50,000,000đ</b>. Thời hạn: 30 ngày.\n\n<em style="color:rgba(200,180,180,.7)">"Ba sẽ lo được con ơi..." — anh nói, giọng run. Rồi bắt đầu làm thêm ca.</em>' },
                storyDebt: { chapter: 'Chương 2 · Sa Thải', title: 'Giông Bão <span style="color:#ff4444">Kép</span>', text: 'Phẫu thuật thành công. Linh đã an toàn.\n\nNhưng hôm qua, công ty thông báo cắt giảm nhân sự do kinh tế khó khăn. Minh nằm trong danh sách layoff. Để duy trì sinh hoạt và chi phí y tế cho con, anh phải vay nặng lãi.\n\nSố tiền cần trả để thoát nợ: <b style="color:#ffd700">150,000,000đ</b>. Thời hạn: 35 ngày.\n\n<em style="color:rgba(200,180,180,.7)">Anh rải hồ sơ khắp nơi, làm freelance thâu đêm. Không có đường lui.</em>' },
                storyHospital: { chapter: 'Chương 3 · Ranh Giới', title: 'Mẹ <span style="color:#e63946">Ung Thư</span>', text: 'Nợ đã trả xong. Minh thở phào — được vài ngày.\n\nMẹ anh từ quê gọi điện. Bác sĩ báo tin dữ: Ung thư dạ dày giai đoạn 2.\n\nChi phí phẫu thuật và xạ trị: <b style="color:#ffd700">300,000,000đ</b>. Bác sĩ cho thời hạn 40 ngày.\n\n<em style="color:rgba(200,180,180,.7)">"Tiền có thể kiếm lại. Nhưng mẹ thì không."</em>' },
                storyShipper: { chapter: 'Chương 4 · Tuyệt Vọng', title: 'Vợ <span style="color:#fbbf24">Cấp Cứu</span>', text: 'Mẹ đã bắt đầu phác đồ điều trị. Tình hình tạm ổn.\n\nNhưng áp lực gia đình khiến vợ Minh suy nhược nặng, mắc hội chứng tiền sản giật đe dọa tính mạng.\n\nChi phí điều trị tích cực (ICU) và chăm sóc đặc biệt: <b style="color:#ffd700">600,000,000đ</b>. Thời hạn: 45 ngày.\n\n<em style="color:rgba(200,180,180,.7)">Minh vắt kiệt chút sinh lực cuối cùng. Anh hứa sẽ bảo vệ gia đình này bằng mọi giá.</em>' },
                
                storyDaughter_female: { chapter: 'Chương 1 · Mẹ Đơn Thân', title: 'Tiền Học <span style="color:#ec4899">Cho Con</span>', text: 'Lan, 32 tuổi, thợ may kiêm bán hàng online.\n\nChồng bỏ đi để lại đống nợ. Con gái nhỏ sắp vào lớp 1 nhưng cô không xoay sở đâu ra tiền đóng học phí và mua sách vở.\n\nCô cần: <b style="color:#ffd700">30,000,000đ</b> để trả tiền nhập học và phí sinh hoạt. Thời hạn: 30 ngày.\n\n<em style="color:rgba(200,180,180,.7)">"Mẹ sẽ không để con phải nghỉ học..." — cô tự nhủ và nhận thêm việc về nhà làm đêm.</em>' },
                storyDebt_female: { chapter: 'Chương 2 · Đe Dọa', title: 'Chủ Nợ <span style="color:#ff4444">Gõ Cửa</span>', text: 'Tiền học của con đã lo xong.\n\nNhưng hôm nay, giang hồ đến tận xưởng đập phá. Chúng là chủ nợ của người chồng cũ tồi tệ. Lãi mẹ đẻ lãi con.\n\nSố tiền bắt buộc phải trả: <b style="color:#ffd700">80,000,000đ</b>. Thời hạn: 35 ngày.\n\n<em style="color:rgba(200,180,180,.7)">Cô bật khóc trong đêm, ngủ 3 tiếng mỗi ngày để cày cuốc. Nếu không trả, chúng sẽ quậy phá cả trường của con gái.</em>' },
                storyHospital_female: { chapter: 'Chương 3 · Cú Sốc', title: 'Trái Tim <span style="color:#e63946">Lỗi Nhịp</span>', text: 'Món nợ đã dứt điểm. Cuộc sống tưởng chừng yên ổn.\n\nĐột nhiên con gái nhỏ ngất xỉu. Bác sĩ Viện Tim chẩn đoán bé bị tứ chứng Fallot — một dạng tim bẩm sinh phức tạp cần phẫu thuật gấp.\n\nChi phí mổ tim: <b style="color:#ffd700">150,000,000đ</b>. Thời hạn: 40 ngày.\n\n<em style="color:rgba(200,180,180,.7)">Lan bán mọi thứ có thể. Mạng sống của con gái là tất cả những gì cô còn lại.</em>' },
                storyShipper_female: { chapter: 'Chương 4 · Báo Hiếu', title: 'Cha <span style="color:#ec4899">Ung Thư Phổi</span>', text: 'Ca mổ thành công, con gái đã hồi phục.\n\nNhưng tin sét đánh ập đến: cha ruột dưới quê ho ra máu, phát hiện ung thư phổi do nhiều năm hút thuốc lá.\n\nChi phí điều trị: <b style="color:#ffd700">300,000,000đ</b>. Thời hạn: 45 ngày.\n\n<em style="color:rgba(200,180,180,.7)">"Cả đời cha vất vả vì con rồi. Hãy để con lo cho cha lần này."</em>' },
                
                storyDaughter_hung: { chapter: 'Chương 1 · Ước Mơ', title: 'Học Phí <span style="color:#34d399">Em Gái</span>', text: 'Hùng, 20 tuổi, sinh viên năm 3. Em gái Hùng vừa đỗ đại học nhưng gia đình không đủ tiền đóng học phí kỳ đầu.\n\nCần gấp: <b style="color:#ffd700">15,000,000đ</b> để em gái không phải bỏ học giữa chừng. Thời hạn: 30 ngày.\n\n<em style="color:rgba(180,255,180,.7)">"Em cứ nhập học đi, tiền nong cứ để anh lo. Anh sẽ làm thêm ở quán net."</em>' },
                storyDebt_hung: { chapter: 'Chương 2 · Cạm Bẫy', title: 'Bị <span style="color:#ff4444">Lừa Đảo</span> Qua Mạng', text: 'Học phí của em đã đóng xong.\n\nNhưng do nôn nóng muốn kiếm nhiều tiền, Hùng sập bẫy lừa đảo việc làm online, mất trắng tiền trọ và mang nợ bạn bè.\n\nSố tiền cần để chuộc lỗi và xoay xở nợ nần: <b style="color:#ffd700">50,000,000đ</b>. Thời hạn: 35 ngày.\n\n<em style="color:rgba(180,255,180,.7)">Hùng nhận 3 công việc một lúc, vừa học vừa làm shipper đến kiệt sức.</em>' },
                storyHospital_hung: { chapter: 'Chương 3 · Tai Ương', title: 'Em Gái <span style="color:#e63946">Ngã Bệnh</span>', text: 'Nợ nần đã êm xuôi.\n\nBất ngờ em gái bị viêm ruột thừa cấp, biến chứng viêm phúc mạc cần mổ và nằm viện dài ngày.\n\nChi phí viện phí: <b style="color:#ffd700">100,000,000đ</b>. Thời hạn: 40 ngày.\n\n<em style="color:rgba(180,255,180,.7)">"Anh xin lỗi vì không chăm sóc em tốt hơn. Anh sẽ lo đủ tiền viện phí."</em>' },
                storyShipper_hung: { chapter: 'Chương 4 · Nghịch Cảnh', title: 'Cha <span style="color:#fbbf24">Suy Thận</span>', text: 'Em gái đã xuất viện an toàn.\n\nTuy nhiên, cha ở quê phát bệnh suy thận mạn tính giai đoạn cuối. Ông cần tiền để chạy thận nhân tạo định kỳ và chờ cơ hội ghép thận.\n\nChi phí khổng lồ: <b style="color:#ffd700">200,000,000đ</b>. Thời hạn: 45 ngày.\n\n<em style="color:rgba(180,255,180,.7)">Cậu sinh viên trẻ kiên cường đối mặt với giông bão. Không lùi bước.</em>' },
                
                storyDaughter_khanh: { chapter: 'Chương 1 · Thử Thách Mới', title: 'Mục Tiêu <span style="color:#a855f7">Thăng Chức</span>', text: 'Khánh, 28 tuổi, nhân viên mẫn cán nhưng có thân hình ngoại cỡ (100kg).\n\nCơ hội thăng chức Trưởng phòng đang mở ra. Nhưng sếp yêu cầu phải hoàn thành KPI vượt trội.\n\nMục tiêu doanh số: <b style="color:#ffd700">20,000,000đ</b>. Thời hạn: 30 ngày.\n\n<em style="color:rgba(216,180,255,.7)">"Mình phải chứng minh cho họ thấy năng lực thực sự, không để bị đánh giá qua vẻ bề ngoài."</em>' },
                storyDebt_khanh: { chapter: 'Chương 2 · Khẳng Định', title: 'Vượt Qua <span style="color:#a855f7">Định Kiến</span>', text: 'KPI ban đầu đã đạt.\n\nNhưng đồng nghiệp bắt đầu gièm pha, cho rằng người ục ịch như Khánh không thể đại diện cho bộ mặt công ty. Sếp giao thêm một dự án lớn để thử thách.\n\nMục tiêu doanh số: <b style="color:#ffd700">60,000,000đ</b>. Thời hạn: 35 ngày.\n\n<em style="color:rgba(216,180,255,.7)">Stress bủa vây từ những lời mỉa mai. Khánh phải cắn răng làm việc.</em>' },
                storyHospital_khanh: { chapter: 'Chương 3 · Sức Ép', title: 'Cạnh Tranh <span style="color:#a855f7">Khốc Liệt</span>', text: 'Dự án thành công. Nhưng đối thủ cạnh tranh vị trí Trưởng phòng dùng thủ đoạn.\n\nSếp yêu cầu Khánh phải chốt được một hợp đồng chiến lược để quyết định ai lên chức.\n\nMục tiêu doanh số: <b style="color:#ffd700">120,000,000đ</b>. Thời hạn: 40 ngày.\n\n<em style="color:rgba(216,180,255,.7)">"Chỉ còn một bước nữa. Mình không thể gục ngã bây giờ."</em>' },
                storyShipper_khanh: { chapter: 'Chương 4 · Trái Ngọt', title: 'Giám Đốc <span style="color:#a855f7">Dự Án</span>', text: 'Hợp đồng đã ký. Nhưng công ty bất ngờ cải tổ, vị trí cao hơn là Giám đốc Dự án.\n\nĐây là thử thách cuối cùng. Khẳng định tài năng và một thân hình khỏe mạnh sẽ là điểm cộng tuyệt đối.\n\nMục tiêu doanh số khổng lồ: <b style="color:#ffd700">300,000,000đ</b>. Thời hạn: 45 ngày.\n\n<em style="color:rgba(216,180,255,.7)">Khánh dồn toàn lực, vừa tập luyện giảm cân vừa chạy nước rút.</em>' },
                
                goalLabel: 'MỤC TIÊU BAN ĐẦU', goalSub1: 'Kiếm đủ trong ', goalSub2: ' ngày · Độ khó: ',
                storyStart: '▶ BẮT ĐẦU', storyBack: '← MENU',
                tutTitle: '📖 HƯỚNG DẪN CHƠI',
                tutMove: '🎮 DI CHUYỂN', tutMoveText: 'Dùng phím <b>W A S D</b> hoặc <b>↑←↓→</b> để di chuyển nhân vật.',
                tutInteract: '⚡ TƯƠNG TÁC', tutInteractText: 'Đi lại gần đồ vật hoặc NPC, nhấn <b>E</b> để tương tác.',
                tutGoal: '🎯 MỤC TIÊU', tutGoalText: 'Kiếm đủ tiền trước khi hết ngày.',
                tutRooms: '🏢 BỐ CỤC PHÒNG',
                tutRoomsText: '• <b>Trên-trái:</b> Văn phòng<br>• <b>Trên-phải:</b> Khu làm đêm<br>• <b>Dưới-trái:</b> Nghỉ ngơi<br>• <b>Dưới-phải:</b> Café & Y tế',
                tutHealth: '❤️ SỨC KHỎE', tutHealthText: '• <b>HP</b> giảm nếu mệt cao<br>• <b>Mệt mỏi</b> tăng khi làm việc<br>• HP = 0 → Game Over!',
                tutNpc: '🗣 ĐỒNG NGHIỆP', tutNpcText: 'Đi gần NPC và nhấn <b>E</b> để nhận lời khuyên!',
                tutPlay: '▶ BẮT ĐẦU CHƠI!',
                npcSays: ' quay sang nói:', npcThanks: '👋 Cảm ơn ',
                npcFatWarn: ' nhìn lo lắng: "Mệt lắm rồi..."', npcHpWarn: ': "Xanh xao quá! Đi khám đi!"',
                // Action Menus
                actDrinksTitle: '🥤 ĐỒ UỐNG <span style="color:rgba(255,215,0,.6);font-size:11px">🕒 1 giờ</span>',
                actDrinksSub: 'Chọn đồ uống tại quán:',
                actDrinksCoffee: '☕ Cà phê',
                actDrinksCoffeeWarn: '-10HP (quá nhiều!)',
                actDrinksMilktea: '🧋 Trà sữa',
                actDrinksWater: '💧 Nước lọc (FREE)',
                actDrinksMilk: '🥛 Sữa tươi',
                actDrinksNo: '🚫 Không uống',
                actNoMoneyTitle: '💸 Không Đủ Tiền',
                actNoMoneySub: 'Cần kiếm thêm!',
                actOk: 'OK',
                actDocTitle: '🏥 KHÁM BỆNH <span style="color:rgba(255,215,0,.6);font-size:11px">🕒 2-4 giờ</span>',
                actDocSub: 'Phòng khám gần công ty:',
                actDocBasic: 'Khám Lâm Sàng cơ bản (Huyết áp, Nhịp tim)',
                actDocFull: 'Khám Tổng Quát: Siêu âm Doppler, Mỡ máu, ECG',
                actDocNo: '🔙 Để sau',
                actExTitle: '🏋 TẬP THỂ DỤC',
                actExSub: 'Tập càng lâu → HP nhiều hơn, giảm mệt nhiều hơn, nhưng tốn năng lượng!',
                actEx30: '🏃 30 phút',
                actEx45: '🏃‍♂️ 45 phút',
                actEx10: '🏋 1 tiếng',
                actEx15: '💪 1 tiếng 30',
                actEx20: '🔥 2 tiếng',
                actExNo: '🔙 Không tập',
                actGameTitle: '🎮 CHƠI GAME',
                actGameSub: 'Giảm mệt mỏi tinh thần thần tốc!',
                actGame30: '🎮 Chơi 30 phút',
                actGame10: '🎮 Chơi 1 tiếng',
                actGame20: '🎮 Chơi 2 tiếng',
                actGame30h: '🎮 Chơi 3 tiếng',
                actGameNo: '🔙 Thôi',
                actSocialTitle: '📱 LƯỚT MXH <span style="color:rgba(255,215,0,.6);font-size:11px">🕒 2 giờ</span>',
                actSocialSub: 'Lướt TikTok, Facebook, Instagram...',
                actSocialWarn: 'Mất thời gian và có thể tăng stress!',
                actSocialBtn: '📱 Lướt 2h',
                actSocialNo: '🔙 Không',
                actRestTitle: '🧘 NGHỈ NGƠI',
                actRestSub: 'Ăn trưa, thư giãn. Phục hồi sức khỏe và giảm mệt mỏi.',
                actRest2: '✅ Nghỉ 2 tiếng',
                actRest4: '✅ Nghỉ 4 tiếng',
                actRest6: '✅ Nghỉ 6 tiếng',
                actRest24: '🛌 Nghỉ 1 ngày',
                actRestNo: '🔙 Làm tiếp',
                actSleepTitle: '🛏 VỀ NHÀ NGỦ',
                actSleepSub: 'Về nhà chăn ấm đệm êm.',
                actSleep2: '😪 Ngủ chợp mắt (2 tiếng)',
                actSleep4: '😪 Ngủ ít (4 tiếng)',
                actSleep6: '😴 Ngủ vừa (6 tiếng)',
                actSleep8: '😴 Ngủ đủ giấc (8 tiếng)',
                actSleepNo: '🔙 Thức tiếp',
                actOt1Title: '⏰ TĂNG CA',
                actOt1Sub: 'Chọn thời gian tăng ca (Tăng tiền, tăng mệt):',
                actOt1_1: 'Tăng ca 1 tiếng',
                actOt1_2: 'Tăng ca 2 tiếng',
                actOt1_3: 'Tăng ca 3 tiếng',
                actOt1_4: 'Tăng ca 4 tiếng',
                actOt1_5: 'Tăng ca 5 tiếng',
                actOt1_6: 'Tăng ca 6 tiếng',
                actOt1No: '🚪 Từ chối',
                actOt2Title: '💼 DỰ ÁN NGOÀI',
                actOt2Sub: 'Startup nhờ làm thêm dự án:',
                actOt2_1: 'Dự án nhỏ (2h)',
                actOt2_2: 'Dự án địa phương (3h)',
                actOt2_3: 'Dự án tầm trung (4h)',
                actOt2_4: 'Dự án trọng điểm (5h)',
                actOt2_5: 'Dự án lớn (8h)',
                actOt2_6: 'Dự án quốc tế (12h)',
                actOt2No: '❌ Từ chối',
                actOt3Title: '🌙 LÀM QUA ĐÊM',
                actOt3Sub: 'Làm suốt đêm — nguy hiểm nhất.',
                actOt3_1: 'Cày đến nửa đêm (4h)',
                actOt3_2: 'Thức trắng đêm (7h)',
                actOt3_3: 'Làm xuyên đêm (9h)',
                actOt3No: '😴 Thôi, đi ngủ',
                actFreeTitle: '💻 FREELANCE & LÀM THÊM',
                actFreeSub: 'Kiếm thêm ngoài linh hoạt:',
                actFree_1: 'Code dạo (3h, Tiền cao)',
                actFree_2: 'Dựng TikTok (2h)',
                actFree_3: 'Đăng PR FB (1h)',
                
                actOt1Title_female: '🧵 LÀM THÊM XƯỞNG MAY',
                actOt1Sub_female: 'Nhận hàng về may gia công để kiếm thêm:',
                actOt1_1_female: 'Nhặt chỉ thừa (1h)', actOt1_2_female: 'May ráp (2h)', actOt1_3_female: 'May ca tối (3h)',
                actOt1_4_female: 'Chạy sạp đồ (4h)', actOt1_5_female: 'Giao hàng sỉ (5h)', actOt1_6_female: 'Thức trắng sửa lỗi (6h)',
                
                actOt3Title_female: '🛍️ BÁN HÀNG CHỢ ĐÊM',
                actOt3Sub_female: 'Livestream và bán hàng tới khuya. Cực kỳ hao tổn sức khỏe:',
                actOt3_1_female: 'Dọn sạp (2h)', actOt3_2_female: 'Livestream (4h)', actOt3_3_female: 'Bán thâu đêm (6h)',
                
                actFreeTitle_female: '💅 LÀM MÓNG & BÁN HÀNG ONLINE',
                actFreeSub_female: 'Làm thêm các việc vặt linh hoạt:',
                actFree_1_female: 'Làm Nail dạo (3h)',
                actFree_2_female: 'Đăng bài bán hàng (2h)',
                actFree_3_female: 'Đóng gói đơn (1h)',
                actFree_4: 'Trồng rau (4h, Ít stress)',
                actFree_5: 'Chạy Shipper (2h, Rất mệt)',
                actFree_6: 'Phục vụ Café (3h)',
                actFree_7: 'Làm thợ cơ khí (5h, Rất hại sức khỏe)',
                actFree_8: 'Viết bài chuẩn SEO (2h)',
                actFree_9: 'Trực tổng đài ca đêm (4h, Stress)',
                actFree_10: 'Phát tờ rơi (1h)',
                actFree_11: 'Khuân vác kho bãi (6h, Kiệt sức)',
                actFree_12: 'Gia sư Tiếng Anh (3h)',
                actFree_13: 'Trông trẻ (4h, Stress)',
                actFree_14: 'Dạy tiếng Việt cho người nước ngoài (2h)',
                actFree_15: 'Làm móng/Nail (3h, Khéo tay)',
                actFree_16: 'Chăm sóc thú cưng (2h, Giảm stress)',
                actFree_17: 'Trợ giảng (4h)',
                actFreeNo: '❌ Nghỉ ngơi',
                actFree: 'Miễn phí',
                actDrinksTitle: '🍽 QUÁN ĂN & ĐỒ UỐNG <span style="color:rgba(255,215,0,.6);font-size:11px">🕒 1 giờ</span>',
                actDrinksSub: 'Chọn đồ ăn hoặc đồ uống:',
                actDrinksCoffee: '☕ Cà phê',
                actDrinksCoffeeWarn: '-10HP (say cà phê!)',
                actDrinksMilktea: '🧋 Trà sữa',
                actDrinksWater: '💧 Nước lọc (FREE)',
                actDrinksMilk: '🥛 Sữa tươi',
                actDrinksMatcha: '🍵 Matcha Latte',
                actDrinksCola: '🥤 Coca cola',
                actDrinksLemon: '🍋 Trà chanh',
                actDrinksFries: '🍟 Khoai tây chiên',
                actDrinksChicken: '🍗 Gà rán',
                actDrinksPizza: '🍕 Pizza',
                actDrinksNoodles: '🍜 Mì tôm',
                actDrinksPho: '🍲 Phở',
                actDrinksFriedRice: '🍛 Cơm rang',
                actDrinksBrokenRice: '🍱 Cơm tấm',
                actDrinksIceCream: '🍦 Kem',
                actDrinksChocolate: '🍫 Chocolate',
                actDrinksBanhCuon: '🌯 Bánh cuốn',
                actDrinksSoup: '🍲 Súp',
                actDrinksPorridge: '🥣 Cháo',
                actDrinksSourSoup: '🥘 Canh chua cá lóc',
                actDrinksBraisedCarp: '🐟 Cá chép om dưa',
                actDrinksBraisedPork: '🍖 Thịt kho tàu',
                actDrinksBoiledEgg: '🥚 Trứng luộc',
                actDrinksFriedEgg: '🍳 Trứng rán',
                actDrinksStickyRice: '🍚 Xôi Chả',
                actDrinksBanhMi: '🥖 Bánh mì kẹp thịt',
                actDrinksHamburger: '🍔 Hamburger',
                actDrinksNo: '🚫 Không ăn gì',
                actDocBuyMeds: '💊 Mua Thuốc',
                actDocHeadacheMeds: '💊 Thuốc Đau Đầu'
            },
            en: {
                newGame: 'NEW GAME', continueGame: 'CONTINUE', aiHealth: 'AI LIFESPAN',
                settings: 'SETTINGS', news: 'NEWS', intro: 'ABOUT', bestRuns: 'BEST RUNS', subtitle: 'a story about the price of ambition',
                settTitle: '⚙ SETTINGS', settSub: 'GAME SETTINGS · v7.0',
                settSound: '🔊 AUDIO', settDiff: '⚔ DIFFICULTY', settLang: '🌐 LANGUAGE',
                settControls: '🎮 CONTROLS', settSave: '💾 SAVE SETTINGS', settBack: '← GO BACK',
                bgm: 'Background Music', sfx: 'Sound Effects',
                easy: 'EASY', normal: 'NORMAL', hard: 'HARD',
                move: 'Move', interact: 'Interact', menuClose: 'Menu / Close', moveAlt: 'Move (alt)',
                moneyLabel: '💰 TOTAL EARNINGS', goalPrefix: 'Target: ', daysLeft: ' days)',
                statusNormal: 'NORMAL', statusTired: 'TIRED', statusWarning: 'CAREFUL', statusDanger: 'DANGER',
                sleptYes: 'Well rested', sleptNo: 'Not slept', cups: ' cups',
                talkTo: '[ E ] Talk to ', interactWith: '[ E ] ',
                overtime: 'Overtime', project: 'Project', overnight: 'Overnight', freelance: 'Freelance',
                sleep: 'Sleep', rest: 'Rest', exercise: 'Exercise', coffee: 'Diner', gaming: 'Gaming', social: 'Social', doctor: 'Doctor',
                descOT: '+$$ OT Pay', descProject: '+$$$ Project Pay', descOvernight: '+$$$$ Late Night Pay', descFreelance: '+$$$ Freelance Pay',
                descSleep: 'Restore HP & Fatigue', descRest: '-25% Fatigue, +5HP',
                descExercise: '+HP, -Stress', descCoffee: 'Reduce fatigue, restore HP', descGaming: '-Stress, +Joy',
                descSocial: '-Fee, +Joy', descDoctor: '+30HP, -20% Fatigue',
                actFree_1: 'Freelance coder (3h)',
                actFree_2: 'Edit TikTok video (2h)',
                actFree_3: 'Post FB ads (1h)',
                actFree_4: 'Farming simulator (4h)',
                actFree_5: 'Delivery driver (2h)',
                actFree_6: 'Cafe Server (3h)',
                actFree_7: 'Mechanic assistant (5h)',
                actFree_8: 'Write SEO Articles (2h)',
                actFree_9: 'Night Call Center (4h)',
                actFree_10: 'Hand out flyers (1h)',
                actFree_11: 'Warehouse Porter (6h)',
                actFree_12: 'English Tutor (3h)',
                actFree_13: 'Babysitting (4h)',
                actFree_14: 'Vietnamese Tutor (2h)',
                actFree_15: 'Nail Technician (3h)',
                actFree_16: 'Pet Sitting (2h)',
                actFree_17: 'Teaching Assistant (4h)',
                actFreeNo: '❌ Rest',
                actOt2_5: 'Large Project (8h)', actOt2_6: 'Intl Project (12h)',
                roomOffice: '📋 OFFICE', roomNight: '🌙 NIGHT ZONE',
                roomRest: '🛏 REST ZONE', roomCafe: '☕ CAFÉ & CLINIC',
                easyDesc: 'Goal -35% · Income +50% · Less fatigue',
                normalDesc: 'Standard goal · Standard fatigue · Standard income',
                hardDesc: 'Goal +50% · Less income · Faster fatigue',
                npc1: ['Watch your health!', 'Take a break if tired!', 'Get enough sleep!', 'Don\'t drink too much coffee!'],
                npc2: ['Be careful of burnout!', 'You should rest a bit.', 'Health is more important than money.', 'Take care of yourself.'],
                npc3: ['It\'s late, go sleep!', 'Don\'t overwork yourself.', 'Sleeping well = better productivity.', 'Too much coffee hurts your heart!'],
                npc4: ['You look pale, go get checked!', 'Your little girl is waiting for you.', 'Don\'t give up, brother.', 'Take a coffee break.'],
                npcChild: ['Daddy, please don\'t work too hard!', 'I want to see you smile, not look so tired.', 'Daddy, take a break and hug me!', 'Health is the most important thing!'],
                npcMom: ['Honey, take a rest.', 'Money is tight, but please don\'t push yourself, I\'m so worried.', 'Your health is our family\'s pillar.', 'Don\'t push yourself too hard, get some sleep.'],
                backMenu: '← MENU', goalWord: 'left: ',
                // HUD labels
                hudEn: '⚡ ENERGY', hudHp: '❤️ HEALTH', hudFat: '😴 FATIGUE',
                hudTi: '🕒 TIME', hudHu: '🍚 HUNGER', hudKn: '📚 KNOWLEDGE',
                hudDay: 'DAY', hudLv: 'LV',
                hudSleep: 'Slept:', hudCoffee: 'Coffee today:', hudStatus: 'Status:',
                hudWife: 'Wife Rel:', hudDaug: 'Daug Rel:',
                hwarn: '⚠ DANGER — TOO FATIGUED!',
                chint: 'WASD: Move · E: Interact · F: Wardrobe · ESC: Menu · ⏳ Time advances per hour',
                wardrobe: 'Wardrobe',
                // Mall items
                mall_jacket: 'Leather Jacket', mall_shoes: 'Sneakers', mall_teddy: 'Big Teddy Bear',
                mall_doll: 'Small Doll', mall_lego: 'Lego Set', mall_flowers: 'Fresh Flowers',
                mall_necklace: 'Necklace', mall_perfume: 'French Perfume', mall_ring: 'Diamond Ring',
                mall_watch: 'Luxury Watch',
                evImpactLbl: 'COST INCURRED', evConfirm: 'UNDERSTOOD — CONTINUE →',
                evNewGoal: 'New target: ', evDaysLeft: ' days)',
                // News labels
                newsHeader: 'NEWS & <span>MEDICINE</span>',
                newsSubtitle: 'Stay updated with the latest health and medical information',
                newsMore: 'READ MORE',
                newsBack: 'BACK TO MENU',
                // News Articles
                articles: [
                    { date: '12/27/2024', title: 'Cardiovascular disease is rejuvenating', desc: 'Every year, 200,000 Vietnamese people die from this disease. Experts warn about modern lifestyles.', url: 'https://suckhoedoisong.vn/benh-tim-mach-dang-ngay-cang-tre-hoa-moi-nam-200000-nguoi-viet-tu-vong-vi-benh-nay-169241227211028683.htm', img: 'https://loremflickr.com/400/200/heart,disease/all?lock=1' },
                    { date: '01/15/2025', title: '7 major breakthroughs in cardiovascular research 2024', desc: 'Explore the latest technologies and treatments from the past year.', url: 'https://thuocsuckhoe.vn/7-tien-bo-lon-trong-nghien-cuu-benh-tim-mach-nam-2024-546', img: 'https://loremflickr.com/400/200/research,medical/all?lock=2' },
                    { date: '02/01/2025', title: 'Stroke & Cardiovascular Stats 2025', desc: 'The latest statistical update from Professional Heart on global stroke status.', url: 'https://professional.heart.org/-/media/phd-files-2/science-news/2/2025-heart-and-stroke-stat-update/stat-update-whats-new/2025-stats-update-whats-new-vietnamese.pdf', img: 'https://loremflickr.com/400/200/brain,stroke/all?lock=3' },
                    { date: '02/10/2025', title: 'Mechanisms of cardiovascular disease from lifestyle', desc: 'Scientific research analyzes the impact of stress and staying up late on heart cells.', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11786524/', img: 'https://loremflickr.com/400/200/lifestyle,health/all?lock=4' },
                    { date: '02/18/2025', title: 'Lancet: Global stroke burden', desc: 'In-depth review from The Lancet on neurological trends and associated risks.', url: 'https://www.thelancet.com/journals/laneur/article/PIIS1474-4422(24)00363-6/abstract', img: 'https://loremflickr.com/400/200/hospital,neurology/all?lock=5' },
                    { date: '02/21/2025', title: 'AHA: Impact of nutrition and exercise', desc: 'Article from the American Heart Association on modifiable risk factors.', url: 'https://www.ahajournals.org/doi/10.1161/JAHA.124.039387', img: 'https://loremflickr.com/400/200/nutrition,running/all?lock=6' },
                    { date: '03/01/2025', title: 'The link between chronic stress and heart attacks', desc: 'Constant high-pressure work increases heart failure risk by 40% in your 30s.', url: '#', img: 'https://loremflickr.com/400/200/stress,work/all?lock=7' },
                    { date: '03/05/2025', title: 'Diet reduces stroke risk by 30%', desc: 'New research confirms eating vegetables saves millions of lives.', url: '#', img: 'https://loremflickr.com/400/200/vegetables,salad/all?lock=8' },
                    { date: '03/10/2025', title: '30 minutes a day: The golden key to circulation', desc: 'No high-intensity gym needed, brisk walking is enough to protect your heart.', url: '#', img: 'https://loremflickr.com/400/200/exercise,walking/all?lock=9' },
                    { date: '03/18/2025', title: 'Sleep deprivation and destruction of neurons', desc: 'Sleeping less than 5 hours a night accelerates cognitive decline and brain aging.', url: '#', img: 'https://loremflickr.com/400/200/sleep,bed/all?lock=10' },
                    { date: '03/22/2025', title: 'AI in early diagnosis of stroke imaging', desc: 'Latest AI technology detects blood clots with up to 98% accuracy.', url: '#', img: 'https://loremflickr.com/400/200/technology,AI/all?lock=11' },
                    { date: '03/25/2025', title: 'Energy drinks and irregular heartbeat', desc: 'Abusing caffeinated beverages increases the risk of sudden arrhythmias in youth.', url: '#', img: 'https://loremflickr.com/400/200/energydrink,heart/all?lock=12' },
                    { date: '03/28/2025', title: 'The harm of sitting for 8 continuous hours', desc: 'Prolonged sitting is the new smoking, increasing the risk of blood clots.', url: '#', img: 'https://loremflickr.com/400/200/sitting,office/all?lock=13' }
                ],
                // App content section
                acHeader: 'ABOUT <span>AI TECHNOLOGY</span>',
                acSub: 'Discover the power of artificial intelligence in protecting health and extending lifespan.',
                acC1T: 'Risk & Stroke Screening',
                acC1D: 'Utilizing machine learning models to analyze symptoms and early detect signs of cardiovascular and neurological risks.',
                acC2T: 'Smart Lifestyle Analysis',
                acC2D: 'Evaluating the impact of sleep habits, work intensity, and nutrition on your baseline health metrics.',
                acC3T: 'Comprehensive Health Prediction',
                acC3D: 'AI evaluates stroke risk and predicts overall health based on WHO/AHA standards, lifestyle, and real-time physiological data.',
                acC4T: '24/7 AI Medical Assistant',
                acC4D: 'Instant answers for clinical symptoms, first-aid knowledge, and prevention instructions for medical emergencies.',
                // AI screen
                aiTag: 'HEALTH MONITOR AI · v2.4', aiTitle: 'AI HEALTH PREDICTION',
                aiDesc: 'Enter your lifestyle data for AI health analysis and risk assessment.',
                aiSectionBasic: 'BASIC INFO', aiSectionSleep: 'SLEEP HABITS',
                aiSectionDiet: 'DIET & EXERCISE', aiSectionRisk: 'RISK BEHAVIORS',
                aiSectionExtra: 'ADDITIONAL NOTES (optional)',
                aiSubmit: '🧬 ANALYZE NOW', aiDisclaimer: '⚠ AI Simulation — Not medical advice',
                aiAnalysisHeader: 'HEALTH ANALYSIS SYSTEM',
                aiAgeLbl: 'CURRENT AGE', aiJobLbl: 'JOB / NGHỀ NGHIỆP', aiHeightLbl: 'HEIGHT (cm)', aiWeightLbl: 'WEIGHT (kg)',
                aiCamVerify: '📸 WEBCAM VERIFICATION', aiCamStart: '📷 Open Camera', aiCamCapture: '📸 CAPTURE', aiCamClose: '✕ Close', aiCamDone: '✅ Captured — AI will estimate age', aiCamRetry: '🔄 Retake',
                aiGenderLbl: 'GENDER', aiMale: 'Male', aiFemale: 'Female', aiBmiLbl: 'BMI (kg/m²)', aiSleepLbl: 'HOURS OF SLEEP PER NIGHT', aiBedtimeLbl: 'USUAL BEDTIME?',
                aiBed: ['Before 10 PM', '11 PM', 'Midnight', '1 AM', '2-3 AM', 'After 4 AM'],
                aiSleepBadLbl: 'NIGHTS OF POOR SLEEP / WEEK', aiDietLbl: 'DIET QUALITY',
                aiDiet: ['Very healthy', 'Fairly healthy', 'Average', 'Lots of fried food, fast food', 'Very poor'],
                aiExeLbl: 'EXERCISE / WEEK', aiExe: ['5+ days/week', '3-4 days/week', '1-2 days/week', 'Never'],
                rcSmoking: '🚬 Smoking', rcAlcohol: '🍺 Heavy alcohol', rcStress: '😰 Chronic stress', rcOverwork: '💼 Work >12h/day', rcNoSocial: '🚫 Social isolation',
                rcCaffeine: '☕ >4 coffees/day', rcInsomnia: '🌙 Awake for 2 days', rcSkipMeal: '🍽 Skip meals often', rcGameAbuse: '🎮 Game >6h/day',
                rcNoBreak: '⚠ Work without breaks', rcSleep3h: '😴 Sleep under 3 hours', rcLongStress: '🧠 Stress > 3 months', rcSedentary: '🪑 Sedentary all day', rcEnergy: '⚡ Abuse energy drinks',
                aiExtraLbl: 'ADDITIONAL NOTES (optional)', aiExtraPlc: 'Ex: Often sleep late, rarely active...', aiIdleTxt: 'Fill in info and click<br>ANALYZE NOW',
                aiAnalyzing: '⏳ ANALYZING...', aiAnalyzingData: 'ANALYZING DATA...', aiScanning: 'SCANNING...',
                aiEstLife: 'ESTIMATED LIFESPAN', aiYearsOld: 'years', aiRiskLevel: 'MỨC ĐỘ RỦI RO', aiImprove: '↑ IMPROVING', aiDecline: '↓ DECLINING',
                aiRiskHealth: 'HEALTH RISK', aiWarnDanger: '⚠ WARNING', aiWarnGood: '✅ POSITIVE', aiDetailAI: 'DETAILED ANALYSIS · AI',
                warnSmoking: 'Smoking reduces lifespan by 8-10 years.', warnInsomnia: 'Staying awake for 2 days increases stroke risk by 300%.', warnSleep3h: 'Sleeping under 3 hours destroys the immune system.',
                warnNoBreak: 'Working without breaks causes chronic exhaustion.', warnLongStress: 'Prolonged stress causes cardiovascular damage.', warnSkipMeal: 'Frequent meal skipping causes malnutrition.',
                warnSleepLess6: 'Sleeping under 6 hours causes severe harm.', warnOverwork: 'Working >12h/day increases stroke risk.', warnBmiHigh: 'High BMI increases cardiovascular risk.',
                warnManyRisks: '⚠ TOO MANY RISK FACTORS — cumulative risk is very high!', warnGoodHabit: 'Current lifestyle is fairly good, keep it up!',
                warnDefaultGood: 'Health is currently in good condition.', warnDefaultBad: 'Needs immediate lifestyle improvement.',
                aiExplain1: 'Analyzed ', aiExplain2: ' risk factors, BMI ', aiExplain3: ', sleep ', aiExplain4: 'h/night.', aiExplain5: 'Maintain good habits and avoid harmful factors.',
                storyDaughter: { chapter: 'Chapter 1 · The Father', title: 'For His <span style="color:#ffd700">Little Girl</span>', text: 'Minh, 38 years old, an ordinary office worker.\n\nHis daughter Linh, 7, was just injured and needs urgent orthopedic surgery.\n\nInitial cost: <b style="color:#ffd700">50,000,000đ</b>. Deadline: 30 days.\n\n<em style="color:rgba(200,180,180,.7)">"I\'ll figure it out, sweetie..." — he said, voice trembling. Then started working overtime.</em>' },
                storyDebt: { chapter: 'Chapter 2 · Layoff', title: 'The <span style="color:#ff4444">Double Storm</span>', text: 'The surgery was successful. Linh is fine.\n\nBut yesterday, his company laid off staff due to economy. Minh was among them. To survive and pay for meds, he borrowed from loan sharks.\n\nAmount due: <b style="color:#ffd700">150,000,000đ</b>. Deadline: 35 days.\n\n<em style="color:rgba(200,180,180,.7)">He applies everywhere, working freelance overnight. No turning back.</em>' },
                storyHospital: { chapter: 'Chapter 3 · The Edge', title: 'Mother\'s <span style="color:#e63946">Cancer</span>', text: 'Debt is paid. Minh breathed a sigh of relief.\n\nHis mother called. Diagnosis: stage 2 stomach cancer.\n\nTreatment cost: <b style="color:#ffd700">300,000,000đ</b>. Deadline: 40 days.\n\n<em style="color:rgba(200,180,180,.7)">"Money can be earned again. But not mom."</em>' },
                storyShipper: { chapter: 'Chapter 4 · Despair', title: 'Wife\'s <span style="color:#fbbf24">Emergency</span>', text: 'Mother has started treatment. Things are stable.\n\nBut the family pressure caused Minh\'s wife severe preeclampsia threatening her life.\n\nICU cost: <b style="color:#ffd700">600,000,000đ</b>. Deadline: 45 days.\n\n<em style="color:rgba(200,180,180,.7)">Minh squeezes out his last drop of energy to protect his family.</em>' },
                
                storyDaughter_female: { chapter: 'Chapter 1 · Single Mother', title: 'For Her <span style="color:#ec4899">Little Girl</span>', text: 'Lan, 32 years old, a tailor and online seller.\n\nHer ex-husband ran away leaving debt. Her daughter needs tuition and books for 1st grade.\n\nShe needs: <b style="color:#ffd700">30,000,000đ</b> for school fees. Deadline: 30 days.\n\n<em style="color:rgba(200,180,180,.7)">"I won\'t let my daughter drop out of school..." — she took on night shifts.</em>' },
                storyDebt_female: { chapter: 'Chapter 2 · The Threat', title: 'Debt Collectors <span style="color:#ff4444">At The Door</span>', text: 'The tuition was paid.\n\nBut today, thugs arrived at her workplace. They are the creditors of her terrible ex-husband.\n\nAmount forced to pay: <b style="color:#ffd700">80,000,000đ</b>. Deadline: 35 days.\n\n<em style="color:rgba(200,180,180,.7)">She cried at night, sleeping 3 hours a day to work. Or they\'ll go to her daughter\'s school.</em>' },
                storyHospital_female: { chapter: 'Chapter 3 · The Shock', title: 'A Broken <span style="color:#e63946">Heart</span>', text: 'The debt is fully paid.\n\nSuddenly her daughter fainted. Doctor diagnosed Tetralogy of Fallot, a complex congenital heart defect needing urgent surgery.\n\nTreatment cost: <b style="color:#ffd700">150,000,000đ</b>. Deadline: 40 days.\n\n<em style="color:rgba(200,180,180,.7)">Lan sells everything. Her daughter\'s life is all she has left.</em>' },
                storyShipper_female: { chapter: 'Chapter 4 · Filial Piety', title: 'Father\'s <span style="color:#ec4899">Lung Cancer</span>', text: 'The surgery was successful.\n\nBut her father in the countryside was diagnosed with lung cancer from years of smoking.\n\nTreatment cost: <b style="color:#ffd700">300,000,000đ</b>. Deadline: 45 days.\n\n<em style="color:rgba(200,180,180,.7)">"Dad sacrificed his whole life for me. Let me take care of him."</em>' },
                
                storyDaughter_hung: { chapter: 'Chapter 1 · Sister\'s Dream', title: 'Sister\'s <span style="color:#34d399">Tuition</span>', text: 'Hung, 20, a university junior. His sister just got into college but they can\'t afford it.\n\nNeeds: <b style="color:#ffd700">15,000,000đ</b> for her tuition. Deadline: 30 days.\n\n<em style="color:rgba(180,255,180,.7)">"Just go to school, I\'ll handle the money. I\'ll work extra shifts."</em>' },
                storyDebt_hung: { chapter: 'Chapter 2 · The Trap', title: 'Online <span style="color:#ff4444">Scam</span>', text: 'Tuition is paid.\n\nBut rushing to make money, Hung fell for an online job scam, losing all savings and borrowing from friends.\n\nDebt to repay: <b style="color:#ffd700">50,000,000đ</b>. Deadline: 35 days.\n\n<em style="color:rgba(180,255,180,.7)">Hung takes on 3 jobs at once, working to exhaustion.</em>' },
                storyHospital_hung: { chapter: 'Chapter 3 · Disaster', title: 'Sister\'s <span style="color:#e63946">Illness</span>', text: 'Debt is cleared.\n\nSuddenly his sister suffers acute appendicitis with complications needing surgery and long hospitalization.\n\nHospital fee: <b style="color:#ffd700">100,000,000đ</b>. Deadline: 40 days.\n\n<em style="color:rgba(180,255,180,.7)">"I will do whatever it takes to pay the hospital bills."</em>' },
                storyShipper_hung: { chapter: 'Chapter 4 · Adversity', title: 'Father\'s <span style="color:#fbbf24">Kidney Failure</span>', text: 'His sister is discharged safely.\n\nHowever, his father developed end-stage renal failure, needing dialysis and a kidney transplant.\n\nMassive cost: <b style="color:#ffd700">200,000,000đ</b>. Deadline: 45 days.\n\n<em style="color:rgba(180,255,180,.7)">The young student bravely faces the storm. No stepping back.</em>' },
                
                storyDaughter_khanh: { chapter: 'Chapter 1 · New Challenge', title: 'Target: <span style="color:#a855f7">Promotion</span>', text: 'Khanh, 28, a hard-working but overweight (100kg) employee.\n\nThe Department Head position is opening up. The boss requires outstanding KPIs to consider him.\n\nSales Target: <b style="color:#ffd700">20,000,000đ</b>. Deadline: 30 days.\n\n<em style="color:rgba(216,180,255,.7)">"I must prove my worth. Don\'t judge a book by its cover."</em>' },
                storyDebt_khanh: { chapter: 'Chapter 2 · Affirmation', title: 'Overcoming <span style="color:#a855f7">Prejudice</span>', text: 'Initial KPI met.\n\nBut colleagues whisper that an overweight guy can\'t represent the company. The boss gives an extra project to test him.\n\nSales Target: <b style="color:#ffd700">60,000,000đ</b>. Deadline: 35 days.\n\n<em style="color:rgba(216,180,255,.7)">Stress from rumors is real. He must endure and work harder.</em>' },
                storyHospital_khanh: { chapter: 'Chapter 3 · Pressure', title: 'Fierce <span style="color:#a855f7">Competition</span>', text: 'Project successful. But a rival plays dirty.\n\nThe boss wants a strategic contract closed to make the final decision.\n\nSales Target: <b style="color:#ffd700">120,000,000đ</b>. Deadline: 40 days.\n\n<em style="color:rgba(216,180,255,.7)">"Just one step left. I can\'t fall now."</em>' },
                storyShipper_khanh: { chapter: 'Chapter 4 · Sweet Fruits', title: 'Project <span style="color:#a855f7">Director</span>', text: 'Contract signed. But the company restructured; the open role is Project Director.\n\nFinal test. Proving his talent and getting into a healthier shape will be a massive plus.\n\nMassive Sales Target: <b style="color:#ffd700">300,000,000đ</b>. Deadline: 45 days.\n\n<em style="color:rgba(216,180,255,.7)">Khanh gives it all, balancing intense workouts and sprinting for work.</em>' },
                
                storyStart: '▶ START', storyBack: '← MENU',
                tutTitle: '📖 HOW TO PLAY',
                tutMove: '🎮 MOVEMENT', tutMoveText: 'Use <b>W A S D</b> or <b>↑←↓→</b> to move your character.',
                tutInteract: '⚡ INTERACT', tutInteractText: 'Walk near objects or NPCs, press <b>E</b> to interact.',
                tutGoal: '🎯 OBJECTIVE', tutGoalText: 'Earn enough money before time runs out.',
                tutRooms: '🏢 ROOM LAYOUT',
                tutRoomsText: '• <b>Top-left:</b> Office<br>• <b>Top-right:</b> Night Zone<br>• <b>Bottom-left:</b> Rest Zone<br>• <b>Bottom-right:</b> Café & Clinic',
                tutHealth: '❤️ HEALTH', tutHealthText: '• <b>HP</b> drops when fatigued<br>• <b>Fatigue</b> increases from work<br>• HP = 0 → Game Over!',
                tutNpc: '🗣 COLLEAGUES', tutNpcText: 'Walk near NPCs and press <b>E</b> for advice!',
                tutPlay: '▶ START PLAYING!',
                npcSays: ' turns and says:', npcThanks: '👋 Thanks ',
                npcFatWarn: ' looks worried: "You look exhausted..."', npcHpWarn: ': "You look pale! See a doctor!"',
                // Action Menus
                actDrinksTitle: '🍽 EATERY & DRINKS <span style="color:rgba(255,215,0,.6);font-size:11px">🕒 1 hour</span>',
                actDrinksSub: 'Choose your food or drink:',
                actDrinksCoffee: '☕ Coffee',
                actDrinksCoffeeWarn: '-10HP (too much!)',
                actDrinksMilktea: '🧋 Milk Tea',
                actDrinksWater: '💧 Water (FREE)',
                actDrinksMilk: '🥛 Fresh Milk',
                actDrinksMatcha: '🍵 Matcha Latte',
                actDrinksCola: '🥤 Coca Cola',
                actDrinksLemon: '🍋 Lemon Tea',
                actDrinksFries: '🍟 Fries',
                actDrinksChicken: '🍗 Fried Chicken',
                actDrinksPizza: '🍕 Pizza',
                actDrinksNoodles: '🍜 Noodles',
                actDrinksPho: '🍲 Pho',
                actDrinksFriedRice: '🍛 Fried Rice',
                actDrinksBrokenRice: '🍱 Broken Rice',
                actDrinksIceCream: '🍦 Ice Cream',
                actDrinksChocolate: '🍫 Chocolate',
                actDrinksBanhCuon: '🌯 Banh Cuon',
                actDrinksSoup: '🍲 Soup',
                actDrinksPorridge: '🥣 Porridge',
                actDrinksSourSoup: '🥘 Snakehead Fish Sour Soup',
                actDrinksBraisedCarp: '🐟 Braised Carp with Melon',
                actDrinksBraisedPork: '🍖 Braised Pork',
                actDrinksBoiledEgg: '🥚 Boiled Egg',
                actDrinksFriedEgg: '🍳 Fried Egg',
                actDrinksStickyRice: '🍚 Sticky Rice with Pork Roll',
                actDrinksBanhMi: '🥖 Banh Mi',
                actDrinksHamburger: '🍔 Hamburger',
                actDrinksNo: '🚫 No thanks',
                actDocBuyMeds: '💊 Buy Medicine',
                actDocHeadacheMeds: '💊 Headache Medicine'
            }
        };